#[derive(Debug)]
pub enum Machine {
    EMNONE, 
    EMM32, 
    EMSPARC, 
    EM386, 
    EM68K, 
    EM88K, 
    EM860, 
    EMMIPS, 
    EMS370, 
    EMMIPSRS3LE,
    EMPARISC,
    EMVPP500,
    EMSPARC32PLUS,
    EM960, 
    EMPPC, 
    EMPPC64, 
    EMS390,
    EMV800, 
    EMFR20, 
    EMRH32, 
    EMRCE, 
    EMARM, 
    EMALPHA, 
    EMSH, 
    EMSPARCV9, 
    EMTRICORE, 
    EMARC, 
    EMH8300, 
    EMH8300H, 
    EMH8S, 
    EMH8500, 
    EMIA64, 
    EMMIPSX, 
    EMCOLDFIRE, 
    EM68HC12, 
    EMMMA, 
    EMPCP, 
    EMNCPU, 
    EMNDR1, 
    EMSTARCORE, 
    EMME16, 
    EMST100, 
    EMTINYJ, 
    EMX8664, 
    EMPDSP, 
    EMPDP10, 
    EMPDP11, 
    EMFX66, 
    EMST9PLUS, 
    EMST7, 
    EM68HC16, 
    EM68HC11, 
    EM68HC08, 
    EM68HC05, 
    EMSVX, 
    EMST19, 
    EMVAX, 
    EMCRIS, 
    EMJAVELIN, 
    EMFIREPATH, 
    EMZSP, 
    EMMMIX, 
    EMHUANY, 
    EMPRISM, 
    EMAVR, 
    EMFR30, 
    EMD10V, 
    EMD30V, 
    EMV850, 
    EMM32R, 
    EMMN10300, 
    EMMN10200, 
    EMPJ, 
    EMOPENRISC, 
    EMARCA5, 
    EMXTENSA, 
    EMVIDEOCORE, 
    EMTMMGPP, 
    EMNS32K, 
    EMTPC, 
    EMSNP1K, 
    EMST200,
    Reserved
}

impl Machine{
    pub fn from_u16(value: u16) -> Option<Machine> {
        match value {
    0 => Some(Machine::EMNONE),	
    1 => Some(Machine::EMM32),	
    2 => Some(Machine::EMSPARC),	
    3 => Some(Machine::EM386),	
    4 => Some(Machine::EM68K),	
    5 => Some(Machine::EM88K),	
    6 => Some(Machine::Reserved),	
    7 => Some(Machine::EM860),	
    8 => Some(Machine::EMMIPS),	
    9 => Some(Machine::EMS370),	
    10 => Some(Machine::EMMIPSRS3LE),	
    11 => Some(Machine::Reserved),	
    15 => Some(Machine::EMPARISC),	
    16 => Some(Machine::Reserved),	
    17 => Some(Machine::EMVPP500),	
    18 => Some(Machine::EMSPARC32PLUS),	
    19 => Some(Machine::EM960),	
    20 => Some(Machine::EMPPC),	
    21 => Some(Machine::EMPPC64),	
    22 => Some(Machine::EMS390),	
    23 => Some(Machine::Reserved),	
    36 => Some(Machine::EMV800),	
    37 => Some(Machine::EMFR20),	
    38 => Some(Machine::EMRH32),	
    39 => Some(Machine::EMRCE),	
    40 => Some(Machine::EMARM),	
    41 => Some(Machine::EMALPHA),	
    42 => Some(Machine::EMSH),	
    43 => Some(Machine::EMSPARCV9),	
    44 => Some(Machine::EMTRICORE),	
    45 => Some(Machine::EMARC),	
    46 => Some(Machine::EMH8300),	
    47 => Some(Machine::EMH8300H),	
    48 => Some(Machine::EMH8S),	
    49 => Some(Machine::EMH8500),	
    50 => Some(Machine::EMIA64),	
    51 => Some(Machine::EMMIPSX),	
    52 => Some(Machine::EMCOLDFIRE),	
    53 => Some(Machine::EM68HC12),	
    54 => Some(Machine::EMMMA),	
    55 => Some(Machine::EMPCP),	
    56 => Some(Machine::EMNCPU),	
    57 => Some(Machine::EMNDR1),	
    58 => Some(Machine::EMSTARCORE),	
    59 => Some(Machine::EMME16),	
    60 => Some(Machine::EMST100),	
    61 => Some(Machine::EMTINYJ),	
    62 => Some(Machine::EMX8664),	
    63 => Some(Machine::EMPDSP),	
    64 => Some(Machine::EMPDP10),	
    65 => Some(Machine::EMPDP11),	
    66 => Some(Machine::EMFX66),	
    67 => Some(Machine::EMST9PLUS),	
    68 => Some(Machine::EMST7),	
    69 => Some(Machine::EM68HC16),	
    70 => Some(Machine::EM68HC11),	
    71 => Some(Machine::EM68HC08),	
    72 => Some(Machine::EM68HC05),	
    73 => Some(Machine::EMSVX),	
    74 => Some(Machine::EMST19),	
    75 => Some(Machine::EMVAX),	
    76 => Some(Machine::EMCRIS),	
    77 => Some(Machine::EMJAVELIN),	
    78 => Some(Machine::EMFIREPATH),	
    79 => Some(Machine::EMZSP),	
    80 => Some(Machine::EMMMIX),	
    81 => Some(Machine::EMHUANY),	
    82 => Some(Machine::EMPRISM),	
    83 => Some(Machine::EMAVR),	
    84 => Some(Machine::EMFR30),	
    85 => Some(Machine::EMD10V),	
    86 => Some(Machine::EMD30V),	
    87 => Some(Machine::EMV850),	
    88 => Some(Machine::EMM32R),	
    89 => Some(Machine::EMMN10300),	
    90 => Some(Machine::EMMN10200),	
    91 => Some(Machine::EMPJ),	
    92 => Some(Machine::EMOPENRISC),	
    93 => Some(Machine::EMARCA5),	
    94 => Some(Machine::EMXTENSA),	
    95 => Some(Machine::EMVIDEOCORE),	
    96 => Some(Machine::EMTMMGPP),	
    97 => Some(Machine::EMNS32K),	
    98 => Some(Machine::EMTPC),	
    99 => Some(Machine::EMSNP1K),	
    100 => Some(Machine::EMST200),	
            _ => None,
        }
    }
}
